"""Fix missing columns in material_drawings and reports

Revision ID: 2f9e6573f385
Revises: 002_tz_features
Create Date: 2026-05-06 03:24:28.459380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9e6573f385'
down_revision: Union[str, Sequence[str], None] = '002_tz_features'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('doc_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('scale',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_constraint('drawings_document_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('material_drawings', schema=None) as batch_op:
        batch_op.drop_constraint('material_drawings_drawing_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('material_drawings_material_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('material_drawings_document_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'materials', ['material_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'drawings', ['drawing_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mark', sa.String(length=255), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('unit')
        batch_op.drop_column('cost')

    with op.batch_alter_table('project_shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_level', sa.String(length=50), nullable=True))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_drawing_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('material_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('drawing_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('document_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('view', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_quantity', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'materials', ['material_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'drawings', ['drawing_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'material_drawings', ['material_drawing_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('name')
        batch_op.drop_column('description')
        batch_op.drop_column('created_at')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('total_quantity')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('view')
        batch_op.drop_column('document_id')
        batch_op.drop_column('drawing_id')
        batch_op.drop_column('material_id')
        batch_op.drop_column('material_drawing_id')

    with op.batch_alter_table('project_shares', schema=None) as batch_op:
        batch_op.drop_column('access_level')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('mark')
        batch_op.drop_column('price')
        batch_op.drop_column('type')

    with op.batch_alter_table('material_drawings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('material_drawings_document_id_fkey', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('material_drawings_material_id_fkey', 'materials', ['material_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('material_drawings_drawing_id_fkey', 'drawings', ['drawing_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drawings_document_id_fkey', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('scale',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('doc_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
